function plot_convergence(results)

xerr2       = results.CG;
xWMserr2      = results.WMs;
xWMrerr2     = results.WMr;
xkerr2      = results.lambda_k;
xkplus1err2 = results.lambda_kplus1;
xrerr2      = results.theta_r;
xmerr2      = results.theta_m;

Maxit = results.Maxit;

figure;
clf;

% Create a tiled layout so that the legend can be placed
% above the entire figure and centered.
t = tiledlayout(1,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax = nexttile(t);

% Iteration indices
iter0  = 0:size(xerr2,2)-1;
iterWMs = 0:size(xWMserr2,2)-1;
iterWMr = 0:size(xWMrerr2,2)-1;
iterK  = 0:size(xkerr2,2)-1;
iterK1 = 0:size(xkplus1err2,2)-1;
iterR  = 0:size(xrerr2,2)-1;
iterM  = 0:size(xmerr2,2)-1;

hold(ax,'on');

h0 = semilogy(ax,iter0,xerr2, ...
    '-', ...
    'LineWidth',2.5);

hWM = semilogy(ax,iterWMs,xWMserr2, ...
    '-.', ...
    'LineWidth',2.5);

hHM = semilogy(ax,iterWMr,xWMrerr2, ...
    '-o', ...
    'LineWidth',2.5, ...
    'MarkerSize',12, ...
    'MarkerIndices',1:2:length(iterWMr));

hK = semilogy(ax,iterK,xkerr2, ...
    '--d', ...
    'LineWidth',2.5, ...
    'MarkerSize',9, ...
    'MarkerIndices',1:2:length(iterK));

hK1 = semilogy(ax,iterK1,xkplus1err2, ...
    '--p', ...
    'LineWidth',2.5, ...
    'MarkerSize',10, ...
    'MarkerIndices',1:2:length(iterK1));

hR = semilogy(ax,iterR,xrerr2, ...
    '--+', ...
    'LineWidth',2.5, ...
    'MarkerSize',9, ...
    'MarkerIndices',1:2:length(iterR));

hM = semilogy(ax,iterM,xmerr2, ...
    ':*', ...
    'LineWidth',2.5, ...
    'MarkerSize',9, ...
    'MarkerIndices',1:2:length(iterM));

hold(ax,'off');

% Axes formatting
grid(ax,'on');
box(ax,'on');

ax.FontSize = 20;
ax.LineWidth = 1;
ax.TickLabelInterpreter = 'latex';

xlabel(ax,'CG iterations', ...
    'Interpreter','latex', ...
    'FontSize',20);

ylabel(ax, ...
    '$\displaystyle \frac{\|x^\ast-\hat{x}_\ell\|_2}{\|x^\ast\|_2}$', ...
    'Interpreter','latex', ...
    'FontSize',20, ...
    'Rotation',90);

title(ax,'', ...
    'Interpreter','latex', ...
    'FontSize',20);

% Use integer iteration ticks
xticks(ax,0:5:Maxit);
xtickangle(ax,0);
ax.YScale = 'log';
ax.YTick = [1e-1 1e0 1e1];
% Shared legend centered at the top
lgd = legend(ax, ...
    [h0,hWM,hHM,hK,hK1,hR,hM], ...
    {'CG', ...
     '$\theta=\theta_{WM,e}$', ...
     '$\theta=\theta_{WM,1/\lambda}$', ...
     '$\theta=\lambda_k$', ...
     '$\theta=\lambda_{k+1}$', ...
     '$\theta=\theta_r$', ...
     '$\theta=\theta_m$'}, ...
    'Interpreter','latex', ...
    'Orientation','horizontal', ...
    'NumColumns',4, ...
    'FontSize',20, ...
    'Box','off');

lgd.Layout.Tile = 'north';

% Figure size suitable for publication
set(gcf, ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 24 16]);
%set(gca,'YScale','log');
% Automatic logarithmic y-axis limits and ticks
ax.YScale = 'log';

yl = ylim(ax);

% Expand limits to nearest powers of 10
emin = floor(log10(yl(1)));
emax = ceil(log10(yl(2)));

% Guarantee at least 3 major ticks
if emax - emin < 2
    mid = round((emin + emax)/2);
    emin = mid - 1;
    emax = mid + 1;
end

ylim(ax,[10^emin 10^emax]);
yticks(ax,10.^(emin:emax));
end
